targets:
  $default:
    builders:
      slang_build_runner:
        options:
          inputFilePattern: json
          namespaces: false
          input_directory: assets/i18n
          output_directory: lib/src/resources
          output_file_name: translations.g.dart
          output_format: single_file